# Generated by Django 3.1.7 on 2021-04-05 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ArticlesApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UsersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliography',
            name='id_users',
            field=models.ForeignKey(db_column='id_users', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='id_badge',
            field=models.ForeignKey(db_column='id_badge', on_delete=django.db.models.deletion.DO_NOTHING, to='UsersApp.badge'),
        ),
        migrations.AlterUniqueTogether(
            name='listequipment',
            unique_together={('id_list_equipment', 'id_article', 'id_equipment')},
        ),
        migrations.AlterUniqueTogether(
            name='bibliography',
            unique_together={('id_bibliography', 'id_article', 'id_users')},
        ),
    ]
