# Generated by Django 3.1.7 on 2021-03-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0002_auto_20210328_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_author',
            field=models.BooleanField(null=True),
        ),
    ]
