# Generated by Django 3.1.7 on 2021-03-28 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0004_auto_20210328_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id_tribut',
            field=models.ForeignKey(db_column='id_tribut', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UsersApp.tribut'),
        ),
    ]
